/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-03-16 at 01:28:01 UTC 
 * Modify at your own risk.
 */

package com.example.placeits.placeitendpoint.model;

/**
 * Model definition for PlaceIt.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the placeitendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PlaceIt extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cat0;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cat1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cat2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean iscategory;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double latit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double longit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer onSchedule;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer schedule;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCat0() {
    return cat0;
  }

  /**
   * @param cat0 cat0 or {@code null} for none
   */
  public PlaceIt setCat0(java.lang.String cat0) {
    this.cat0 = cat0;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCat1() {
    return cat1;
  }

  /**
   * @param cat1 cat1 or {@code null} for none
   */
  public PlaceIt setCat1(java.lang.String cat1) {
    this.cat1 = cat1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCat2() {
    return cat2;
  }

  /**
   * @param cat2 cat2 or {@code null} for none
   */
  public PlaceIt setCat2(java.lang.String cat2) {
    this.cat2 = cat2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public PlaceIt setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public PlaceIt setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIscategory() {
    return iscategory;
  }

  /**
   * @param iscategory iscategory or {@code null} for none
   */
  public PlaceIt setIscategory(java.lang.Boolean iscategory) {
    this.iscategory = iscategory;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLatit() {
    return latit;
  }

  /**
   * @param latit latit or {@code null} for none
   */
  public PlaceIt setLatit(java.lang.Double latit) {
    this.latit = latit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLongit() {
    return longit;
  }

  /**
   * @param longit longit or {@code null} for none
   */
  public PlaceIt setLongit(java.lang.Double longit) {
    this.longit = longit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOnSchedule() {
    return onSchedule;
  }

  /**
   * @param onSchedule onSchedule or {@code null} for none
   */
  public PlaceIt setOnSchedule(java.lang.Integer onSchedule) {
    this.onSchedule = onSchedule;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSchedule() {
    return schedule;
  }

  /**
   * @param schedule schedule or {@code null} for none
   */
  public PlaceIt setSchedule(java.lang.Integer schedule) {
    this.schedule = schedule;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public PlaceIt setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public PlaceIt setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * @param userName userName or {@code null} for none
   */
  public PlaceIt setUserName(java.lang.String userName) {
    this.userName = userName;
    return this;
  }

  @Override
  public PlaceIt set(String fieldName, Object value) {
    return (PlaceIt) super.set(fieldName, value);
  }

  @Override
  public PlaceIt clone() {
    return (PlaceIt) super.clone();
  }

}
