/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-03-16 at 01:28:01 UTC 
 * Modify at your own risk.
 */

package com.example.placeits.placeitendpoint;

/**
 * Service definition for Placeitendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PlaceitendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Placeitendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the placeitendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://analog-foundry-505.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "placeitendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Placeitendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Placeitendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPlaceIt".
   *
   * This request holds the parameters needed by the the placeitendpoint server.  After setting any
   * optional parameters, call the {@link GetPlaceIt#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPlaceIt getPlaceIt(java.lang.Long id) throws java.io.IOException {
    GetPlaceIt result = new GetPlaceIt(id);
    initialize(result);
    return result;
  }

  public class GetPlaceIt extends PlaceitendpointRequest<com.example.placeits.placeitendpoint.model.PlaceIt> {

    private static final String REST_PATH = "placeit/{id}";

    /**
     * Create a request for the method "getPlaceIt".
     *
     * This request holds the parameters needed by the the placeitendpoint server.  After setting any
     * optional parameters, call the {@link GetPlaceIt#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPlaceIt#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPlaceIt(java.lang.Long id) {
      super(Placeitendpoint.this, "GET", REST_PATH, null, com.example.placeits.placeitendpoint.model.PlaceIt.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPlaceIt setAlt(java.lang.String alt) {
      return (GetPlaceIt) super.setAlt(alt);
    }

    @Override
    public GetPlaceIt setFields(java.lang.String fields) {
      return (GetPlaceIt) super.setFields(fields);
    }

    @Override
    public GetPlaceIt setKey(java.lang.String key) {
      return (GetPlaceIt) super.setKey(key);
    }

    @Override
    public GetPlaceIt setOauthToken(java.lang.String oauthToken) {
      return (GetPlaceIt) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPlaceIt setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPlaceIt) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPlaceIt setQuotaUser(java.lang.String quotaUser) {
      return (GetPlaceIt) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPlaceIt setUserIp(java.lang.String userIp) {
      return (GetPlaceIt) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPlaceIt setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPlaceIt set(String parameterName, Object value) {
      return (GetPlaceIt) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPlaceIt".
   *
   * This request holds the parameters needed by the the placeitendpoint server.  After setting any
   * optional parameters, call the {@link InsertPlaceIt#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.placeits.placeitendpoint.model.PlaceIt}
   * @return the request
   */
  public InsertPlaceIt insertPlaceIt(com.example.placeits.placeitendpoint.model.PlaceIt content) throws java.io.IOException {
    InsertPlaceIt result = new InsertPlaceIt(content);
    initialize(result);
    return result;
  }

  public class InsertPlaceIt extends PlaceitendpointRequest<com.example.placeits.placeitendpoint.model.PlaceIt> {

    private static final String REST_PATH = "placeit";

    /**
     * Create a request for the method "insertPlaceIt".
     *
     * This request holds the parameters needed by the the placeitendpoint server.  After setting any
     * optional parameters, call the {@link InsertPlaceIt#execute()} method to invoke the remote
     * operation. <p> {@link InsertPlaceIt#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.placeits.placeitendpoint.model.PlaceIt}
     * @since 1.13
     */
    protected InsertPlaceIt(com.example.placeits.placeitendpoint.model.PlaceIt content) {
      super(Placeitendpoint.this, "POST", REST_PATH, content, com.example.placeits.placeitendpoint.model.PlaceIt.class);
    }

    @Override
    public InsertPlaceIt setAlt(java.lang.String alt) {
      return (InsertPlaceIt) super.setAlt(alt);
    }

    @Override
    public InsertPlaceIt setFields(java.lang.String fields) {
      return (InsertPlaceIt) super.setFields(fields);
    }

    @Override
    public InsertPlaceIt setKey(java.lang.String key) {
      return (InsertPlaceIt) super.setKey(key);
    }

    @Override
    public InsertPlaceIt setOauthToken(java.lang.String oauthToken) {
      return (InsertPlaceIt) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPlaceIt setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPlaceIt) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPlaceIt setQuotaUser(java.lang.String quotaUser) {
      return (InsertPlaceIt) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPlaceIt setUserIp(java.lang.String userIp) {
      return (InsertPlaceIt) super.setUserIp(userIp);
    }

    @Override
    public InsertPlaceIt set(String parameterName, Object value) {
      return (InsertPlaceIt) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPlaceIt".
   *
   * This request holds the parameters needed by the the placeitendpoint server.  After setting any
   * optional parameters, call the {@link ListPlaceIt#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPlaceIt listPlaceIt() throws java.io.IOException {
    ListPlaceIt result = new ListPlaceIt();
    initialize(result);
    return result;
  }

  public class ListPlaceIt extends PlaceitendpointRequest<com.example.placeits.placeitendpoint.model.CollectionResponsePlaceIt> {

    private static final String REST_PATH = "placeit";

    /**
     * Create a request for the method "listPlaceIt".
     *
     * This request holds the parameters needed by the the placeitendpoint server.  After setting any
     * optional parameters, call the {@link ListPlaceIt#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListPlaceIt#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPlaceIt() {
      super(Placeitendpoint.this, "GET", REST_PATH, null, com.example.placeits.placeitendpoint.model.CollectionResponsePlaceIt.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPlaceIt setAlt(java.lang.String alt) {
      return (ListPlaceIt) super.setAlt(alt);
    }

    @Override
    public ListPlaceIt setFields(java.lang.String fields) {
      return (ListPlaceIt) super.setFields(fields);
    }

    @Override
    public ListPlaceIt setKey(java.lang.String key) {
      return (ListPlaceIt) super.setKey(key);
    }

    @Override
    public ListPlaceIt setOauthToken(java.lang.String oauthToken) {
      return (ListPlaceIt) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPlaceIt setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPlaceIt) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPlaceIt setQuotaUser(java.lang.String quotaUser) {
      return (ListPlaceIt) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPlaceIt setUserIp(java.lang.String userIp) {
      return (ListPlaceIt) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPlaceIt setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPlaceIt setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPlaceIt set(String parameterName, Object value) {
      return (ListPlaceIt) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePlaceIt".
   *
   * This request holds the parameters needed by the the placeitendpoint server.  After setting any
   * optional parameters, call the {@link RemovePlaceIt#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePlaceIt removePlaceIt(java.lang.Long id) throws java.io.IOException {
    RemovePlaceIt result = new RemovePlaceIt(id);
    initialize(result);
    return result;
  }

  public class RemovePlaceIt extends PlaceitendpointRequest<Void> {

    private static final String REST_PATH = "placeit/{id}";

    /**
     * Create a request for the method "removePlaceIt".
     *
     * This request holds the parameters needed by the the placeitendpoint server.  After setting any
     * optional parameters, call the {@link RemovePlaceIt#execute()} method to invoke the remote
     * operation. <p> {@link RemovePlaceIt#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePlaceIt(java.lang.Long id) {
      super(Placeitendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePlaceIt setAlt(java.lang.String alt) {
      return (RemovePlaceIt) super.setAlt(alt);
    }

    @Override
    public RemovePlaceIt setFields(java.lang.String fields) {
      return (RemovePlaceIt) super.setFields(fields);
    }

    @Override
    public RemovePlaceIt setKey(java.lang.String key) {
      return (RemovePlaceIt) super.setKey(key);
    }

    @Override
    public RemovePlaceIt setOauthToken(java.lang.String oauthToken) {
      return (RemovePlaceIt) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePlaceIt setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePlaceIt) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePlaceIt setQuotaUser(java.lang.String quotaUser) {
      return (RemovePlaceIt) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePlaceIt setUserIp(java.lang.String userIp) {
      return (RemovePlaceIt) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePlaceIt setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePlaceIt set(String parameterName, Object value) {
      return (RemovePlaceIt) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePlaceIt".
   *
   * This request holds the parameters needed by the the placeitendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePlaceIt#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.placeits.placeitendpoint.model.PlaceIt}
   * @return the request
   */
  public UpdatePlaceIt updatePlaceIt(com.example.placeits.placeitendpoint.model.PlaceIt content) throws java.io.IOException {
    UpdatePlaceIt result = new UpdatePlaceIt(content);
    initialize(result);
    return result;
  }

  public class UpdatePlaceIt extends PlaceitendpointRequest<com.example.placeits.placeitendpoint.model.PlaceIt> {

    private static final String REST_PATH = "placeit";

    /**
     * Create a request for the method "updatePlaceIt".
     *
     * This request holds the parameters needed by the the placeitendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePlaceIt#execute()} method to invoke the remote
     * operation. <p> {@link UpdatePlaceIt#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.placeits.placeitendpoint.model.PlaceIt}
     * @since 1.13
     */
    protected UpdatePlaceIt(com.example.placeits.placeitendpoint.model.PlaceIt content) {
      super(Placeitendpoint.this, "PUT", REST_PATH, content, com.example.placeits.placeitendpoint.model.PlaceIt.class);
    }

    @Override
    public UpdatePlaceIt setAlt(java.lang.String alt) {
      return (UpdatePlaceIt) super.setAlt(alt);
    }

    @Override
    public UpdatePlaceIt setFields(java.lang.String fields) {
      return (UpdatePlaceIt) super.setFields(fields);
    }

    @Override
    public UpdatePlaceIt setKey(java.lang.String key) {
      return (UpdatePlaceIt) super.setKey(key);
    }

    @Override
    public UpdatePlaceIt setOauthToken(java.lang.String oauthToken) {
      return (UpdatePlaceIt) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePlaceIt setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePlaceIt) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePlaceIt setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePlaceIt) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePlaceIt setUserIp(java.lang.String userIp) {
      return (UpdatePlaceIt) super.setUserIp(userIp);
    }

    @Override
    public UpdatePlaceIt set(String parameterName, Object value) {
      return (UpdatePlaceIt) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Placeitendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Placeitendpoint}. */
    @Override
    public Placeitendpoint build() {
      return new Placeitendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PlaceitendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPlaceitendpointRequestInitializer(
        PlaceitendpointRequestInitializer placeitendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(placeitendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
